In [5]:
import requests
import re
import pandas as pd
import json
import time
import os
from dotenv import load_dotenv
from google import genai
from google.genai import types
load_dotenv()
api_key = os.getenv("GEMINI_API_KEY")
os.environ["API_KEY"] = api_key
url = "https://api-v1.zyrooai.com/api/v1/math-classifier/interview/questions"

response = requests.get(url)
data = response.json()
df = pd.DataFrame(data['data'])

print(f"Data Loaded: {len(df)} questions found.")
df.head(10)

Data Loaded: 67 questions found.

,id,grade,question,answer,section,label,options
0,P3-002,P3,What is the remainder when 3079 is divided by 8?,7,Section B,"{'strand': 'NUMBER AND ALGEBRA', 'subStrand': ...",NaN
1,P3-006,P3,Ethan left his home at 10:45 am and took 25 mi...,(a) 35 min\n(b) 1:10 pm,Section C,"{'strand': 'MEASUREMENT AND GEOMETRY', 'subStr...",NaN
2,P3-012,P3,5 x 6 = _____,(2) 5 + 5 + 5 + 5 + 5 + 5,Section A,"{'strand': 'NUMBER AND ALGEBRA', 'subStrand': ...","[5 x 5 x 5 x 5 x 5 x5, 5 + 5 + 5 + 5 + 5 + 5, ..."
3,P3-013,P3,Mr Tan bought 6 loaves of bread. Each loaf is ...,(3) 48,Section A,"{'strand': 'NUMBER AND ALGEBRA', 'subStrand': ...","[2, 14, 48, 68]"
4,P3-014,P3,Mr Aw had $650. He had $127 more than Mr Goh. ...,523,Section B,"{'strand': 'NUMBER AND ALGEBRA', 'subStrand': ...",NaN
5,P3-015,P3,Mrs Siva has 650 sweets. She packed all the sw...,2,Section B,"{'strand': 'NUMBER AND ALGEBRA', 'subStrand': ...",NaN
6,P3-016,P3,"4 thousands, 6 hundreds and 9 ones is the same...",(2) 4609,Section A,"{'strand': 'NUMBER AND ALGEBRA', 'subStrand': ...","[4069, 4609, 4690, 4960]"
7,P3-017,P3,What is the missing number in the following nu...,(3) 2425,Section A,"{'strand': 'NUMBER AND ALGEBRA', 'subStrand': ...","[2405, 2415, 2425, 2435]"
8,P3-018,P3,"I am a number between 20 and 40, You can find ...",(1) 24,Section A,"{'strand': 'NUMBER AND ALGEBRA', 'subStrand': ...","[24, 28, 30, 32]"
9,P3-019,P3,Write 9544 in words.,nine thousand five hundred and forty-four,Section B,"{'strand': 'NUMBER AND ALGEBRA', 'subStrand': ...",NaN

In [ ]:
syllabus_df = pd.read_csv('Syllabus.csv')
syllabus_df[['strand', 'subStrand', 'topic']] = syllabus_df[['strand', 'subStrand', 'topic']].ffill()
def clean_topic(text):
    if pd.isna(text):
        return text
    # This regex looks for digits and a dot at the start: "^[0-9]+\.\s*"
    return re.sub(r'^[0-9]+\.\s*', '', str(text))
syllabus_df['topic'] = syllabus_df['topic'].apply(clean_topic)

syllabus_df['loId'] = (
    syllabus_df['grade'].astype(str) + ":" + 
    syllabus_df['subStrand'].astype(str) + ":" + 
    syllabus_df['ref'].astype(str)
)
syllabus_df.head(5)

,strand,subStrand,topic,ref,learningOutcome,grade,loId
0,NUMBER AND ALGEBRA,WHOLE NUMBERS,Numbers up to 10 000,1.1.1,counting in hundreds/thousands,P3,P3:WHOLE NUMBERS:1.1.1
1,NUMBER AND ALGEBRA,WHOLE NUMBERS,Numbers up to 10 000,1.1.2,"number notation, representations and place val...",P3,P3:WHOLE NUMBERS:1.1.2
2,NUMBER AND ALGEBRA,WHOLE NUMBERS,Numbers up to 10 000,1.1.3,reading and writing numbers in numerals and in...,P3,P3:WHOLE NUMBERS:1.1.3
3,NUMBER AND ALGEBRA,WHOLE NUMBERS,Numbers up to 10 000,1.1.4,comparing and ordering numbers,P3,P3:WHOLE NUMBERS:1.1.4
4,NUMBER AND ALGEBRA,WHOLE NUMBERS,Numbers up to 10 000,1.1.5,patterns in number sequences,P3,P3:WHOLE NUMBERS:1.1.5

In [4]:
syllabus_knowledge_base = ""
for _, row in syllabus_df.iterrows():
    loId = f"{row['grade']}:{row['subStrand']}:{row['ref']}"
    syllabus_knowledge_base += (
        f"loId: {loId} | Strand: {row['strand']} | SubStrand: {row['subStrand']} | "
        f"Topic: {row['topic']} | Outcome: {row['learningOutcome']}\n"
    )
syllabus_knowledge_base

'loId: P3:WHOLE NUMBERS:1.1.1 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Numbers up to 10 000 | Outcome: counting in hundreds/thousands\nloId: P3:WHOLE NUMBERS:1.1.2 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Numbers up to 10 000 | Outcome: number notation, representations and place values (thousands, hundreds, tens, ones)\nloId: P3:WHOLE NUMBERS:1.1.3 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Numbers up to 10 000 | Outcome: reading and writing numbers in numerals and in words\nloId: P3:WHOLE NUMBERS:1.1.4 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Numbers up to 10 000 | Outcome: comparing and ordering numbers\nloId: P3:WHOLE NUMBERS:1.1.5 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Numbers up to 10 000 | Outcome: patterns in number sequences\nloId: P3:WHOLE NUMBERS:1.2.1 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Addition and Subtraction | Outcome: addition and subtraction algorithms (up to 4 digits)\nloId: P3:WHOLE NUMBERS:1.2.2 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Addition and Subtraction | Outcome: mental calculation involving addition and subtraction of two 2-digit numbers\nloId: P3:WHOLE NUMBERS:1.3.1 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Multiplication and Division | Outcome: multiplication tables of 6, 7, 8 and 9\nloId: P3:WHOLE NUMBERS:1.3.2 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Multiplication and Division | Outcome: multiplying and dividing within the multiplication tables\nloId: P3:WHOLE NUMBERS:1.3.3 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Multiplication and Division | Outcome: division with remainder\nloId: P3:WHOLE NUMBERS:1.3.4 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Multiplication and Division | Outcome: multiplication and division algorithms (up to 3 digits by 1 digit)\nloId: P3:WHOLE NUMBERS:1.3.5 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Multiplication and Division | Outcome: mental calculation involving multiplication and division within multiplication tables\nloId: P3:FRACTIONS:2.1.1 | Strand: NUMBER AND ALGEBRA | SubStrand: FRACTIONS | Topic: Equivalent fractions | Outcome: equivalent fractions\nloId: P3:FRACTIONS:2.1.2 | Strand: NUMBER AND ALGEBRA | SubStrand: FRACTIONS | Topic: Equivalent fractions | Outcome: expressing a fraction in its simplest form\nloId: P3:FRACTIONS:2.1.3 | Strand: NUMBER AND ALGEBRA | SubStrand: FRACTIONS | Topic: Equivalent fractions | Outcome: comparing and ordering unlike fractions with denominators of given fractions not exceeding 12\nloId: P3:FRACTIONS:2.1.4 | Strand: NUMBER AND ALGEBRA | SubStrand: FRACTIONS | Topic: Equivalent fractions | Outcome: writing the equivalent fraction of a fraction given the denominator or the numerator\nloId: P3:FRACTIONS:2.2.1 | Strand: NUMBER AND ALGEBRA | SubStrand: FRACTIONS | Topic: Addition and Subtraction | Outcome: adding and subtracting two related fractions within one whole with denominators of given fractions not exceeding 12\nloId: P3:MONEY:3.1.1 | Strand: NUMBER AND ALGEBRA | SubStrand: MONEY | Topic: Money | Outcome: adding and subtracting money in decimal notation\nloId: P3:MEASUREMENT:4.1.1 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: MEASUREMENT | Topic: Length, Mass and Volume | Outcome: measuring • length in kilometres (km) • volume of liquid in millilitres (ml)\nloId: P3:MEASUREMENT:4.1.2 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: MEASUREMENT | Topic: Length, Mass and Volume | Outcome: measuring length/mass/volume (of liquid) in compound units\nloId: P3:MEASUREMENT:4.1.3 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: MEASUREMENT | Topic: Length, Mass and Volume | Outcome: converting a measurement in compound units to the smaller unit, and vice versa • kilometres and metres • metres and centimetres • kilograms and grams • litres and millilitres (numbers involved should be within easy manipulation)\nloId: P3:MEASUREMENT:4.2.1 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: MEASUREMENT | Topic: Time | Outcome: measuring time in seconds\nloId: P3:MEASUREMENT:4.2.2 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: MEASUREMENT | Topic: Time | Outcome: finding the starting time, finishing time or duration given the other two quantities\nloId: P3:MEASUREMENT:4.2.3 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: MEASUREMENT | Topic: Time | Outcome: 24-hour clock\nloId: P3:AREA AND VOLUME:5.1.1 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: AREA AND VOLUME | Topic: Area and Perimeter | Outcome: concepts of area and perimeter of a plane figure\nloId: P3:AREA AND VOLUME:5.1.2 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: AREA AND VOLUME | Topic: Area and Perimeter | Outcome: measuring area in square units, cm2 and m2, excluding conversion between cm2 and m2\nloId: P3:AREA AND VOLUME:5.1.3 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: AREA AND VOLUME | Topic: Area and Perimeter | Outcome: perimeter of • rectilinear figure • rectangle • square\nloId: P3:AREA AND VOLUME:5.1.4 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: AREA AND VOLUME | Topic: Area and Perimeter | Outcome: area of rectangle/square\nloId: P3:GEOMETRY:6.1.1 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: GEOMETRY | Topic: Angles | Outcome: concepts of angle\nloId: P3:GEOMETRY:6.1.2 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: GEOMETRY | Topic: Angles | Outcome: right angles, angles greater than/smaller than a right angle\nloId: P3:GEOMETRY:6.2.1 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: GEOMETRY | Topic: Perpendicular and Parallel Lines | Outcome: perpendicular and parallel lines\nloId: P3:GEOMETRY:6.2.2 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: GEOMETRY | Topic: Perpendicular and Parallel Lines | Outcome: drawing perpendicular and parallel lines\nloId: P3:DATA REPRESENTATION AND INTERPRETATION:7.1.1 | Strand: STATISTICS | SubStrand: DATA REPRESENTATION AND INTERPRETATION | Topic: Bar Graphs | Outcome: reading and interpreting data from bar graphs\nloId: P3:DATA REPRESENTATION AND INTERPRETATION:7.1.2 | Strand: STATISTICS | SubStrand: DATA REPRESENTATION AND INTERPRETATION | Topic: Bar Graphs | Outcome: using different scales on axis\nloId: P4:WHOLE NUMBERS:1.1.1 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Numbers up to 100 000 | Outcome: number notation, representations and place values (ten thousands, thousands, hundreds, tens, ones)\nloId: P4:WHOLE NUMBERS:1.1.2 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Numbers up to 100 000 | Outcome: reading and writing numbers in numerals and in words\nloId: P4:WHOLE NUMBERS:1.1.3 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Numbers up to 100 000 | Outcome: comparing and ordering numbers\nloId: P4:WHOLE NUMBERS:1.1.4 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Numbers up to 100 000 | Outcome: patterns in number sequences\nloId: P4:WHOLE NUMBERS:1.1.5 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Numbers up to 100 000 | Outcome: rounding numbers to the nearest 10, 100 or 1000\nloId: P4:WHOLE NUMBERS:1.1.6 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Numbers up to 100 000 | Outcome: use of ≈\nloId: P4:WHOLE NUMBERS:1.2.1 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Factors and Multiples | Outcome: factors, multiples and their relationship\nloId: P4:WHOLE NUMBERS:1.2.2 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Factors and Multiples | Outcome: determining if a 1-digit number is a factor of a given number within 100\nloId: P4:WHOLE NUMBERS:1.2.3 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Factors and Multiples | Outcome: finding the common factors of two given numbers\nloId: P4:WHOLE NUMBERS:1.2.4 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Factors and Multiples | Outcome: determining if a number is a multiple of a given 1-digit number\nloId: P4:WHOLE NUMBERS:1.2.5 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Factors and Multiples | Outcome: finding the common multiples of two given 1-digit numbers\nloId: P4:WHOLE NUMBERS:1.3.1 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Four Operations | Outcome: multiplication algorithm: • up to 4 digits by 1 digit • up to 3 digits by 2 digits\nloId: P4:WHOLE NUMBERS:1.3.2 | Strand: NUMBER AND ALGEBRA | SubStrand: WHOLE NUMBERS | Topic: Four Operations | Outcome: division algorithm (up to 4 digits by 1 digit)\nloId: P4:FRACTIONS:2.1.1 | Strand: NUMBER AND ALGEBRA | SubStrand: FRACTIONS | Topic: Mixed Numbers and Improper Fractions | Outcome: mixed numbers, improper fractions and their relationship\nloId: P4:FRACTIONS:2.2.1 | Strand: NUMBER AND ALGEBRA | SubStrand: FRACTIONS | Topic: Fraction of a Set | Outcome: fraction as part of a set\nloId: P4:FRACTIONS:2.3.1 | Strand: NUMBER AND ALGEBRA | SubStrand: FRACTIONS | Topic: Addition and Subtraction | Outcome: adding and subtracting fractions with denominators of given fractions not exceeding 12 and not more than two different denominators\nloId: P4:DECIMALS:3.1.1 | Strand: NUMBER AND ALGEBRA | SubStrand: DECIMALS | Topic: Decimals up to 3 decimal places | Outcome: notation and place values (tenths, hundredths, thousandths)\nloId: P4:DECIMALS:3.1.2 | Strand: NUMBER AND ALGEBRA | SubStrand: DECIMALS | Topic: Decimals up to 3 decimal places | Outcome: comparing and ordering decimals\nloId: P4:DECIMALS:3.1.3 | Strand: NUMBER AND ALGEBRA | SubStrand: DECIMALS | Topic: Decimals up to 3 decimal places | Outcome: expressing decimals as fractions\nloId: P4:DECIMALS:3.1.4 | Strand: NUMBER AND ALGEBRA | SubStrand: DECIMALS | Topic: Decimals up to 3 decimal places | Outcome: expressing fractions as decimals when the denominator is a factor of 10 or 100\nloId: P4:DECIMALS:3.1.5 | Strand: NUMBER AND ALGEBRA | SubStrand: DECIMALS | Topic: Decimals up to 3 decimal places | Outcome: rounding decimals to • the nearest whole number • 1 decimal place • 2 decimal places\nloId: P4:DECIMALS:3.2.1 | Strand: NUMBER AND ALGEBRA | SubStrand: DECIMALS | Topic: Addition and Subtraction | Outcome: adding and subtracting decimals (up to 2 decimal places)\nloId: P4:DECIMALS:3.3.1 | Strand: NUMBER AND ALGEBRA | SubStrand: DECIMALS | Topic: Multiplication and Division | Outcome: multiplying and dividing decimals (up to 2 decimal places) by a 1-digit whole number\nloId: P4:DECIMALS:3.3.2 | Strand: NUMBER AND ALGEBRA | SubStrand: DECIMALS | Topic: Multiplication and Division | Outcome: dividing a whole number by a whole number with quotient as a decimal\nloId: P4:DECIMALS:3.3.3 | Strand: NUMBER AND ALGEBRA | SubStrand: DECIMALS | Topic: Multiplication and Division | Outcome: rounding answers to a specified degree of accuracy\nloId: P4:AREA AND VOLUME:4.1.1 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: AREA AND VOLUME | Topic: Area and Perimeter | Outcome: finding one dimension of a rectangle given the other dimension and its area/perimeter\nloId: P4:AREA AND VOLUME:4.1.2 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: AREA AND VOLUME | Topic: Area and Perimeter | Outcome: finding the length of one side of a square given its area/perimeter\nloId: P4:AREA AND VOLUME:4.1.3 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: AREA AND VOLUME | Topic: Area and Perimeter | Outcome: finding the area and perimeter of composite figures made up of rectangles and squares\nloId: P4:GEOMETRY:5.1.1 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: GEOMETRY | Topic: Angles | Outcome: using notation such as ∠ABC and ∠a to name angles\nloId: P4:GEOMETRY:5.1.2 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: GEOMETRY | Topic: Angles | Outcome: measuring angles in degrees\nloId: P4:GEOMETRY:5.1.3 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: GEOMETRY | Topic: Angles | Outcome: drawing an angle of given size\nloId: P4:GEOMETRY:5.2.1 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: GEOMETRY | Topic: Rectangle and Square | Outcome: properties of rectangle and square, excluding diagonal properties\nloId: P4:GEOMETRY:5.2.2 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: GEOMETRY | Topic: Rectangle and Square | Outcome: drawing rectangles and squares\nloId: P4:GEOMETRY:5.3.1 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: GEOMETRY | Topic: Line Symmetry | Outcome: identifying symmetric figures\nloId: P4:GEOMETRY:5.3.2 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: GEOMETRY | Topic: Line Symmetry | Outcome: determining whether a straight line is a line of symmetry of a symmetric figure\nloId: P4:GEOMETRY:5.3.3 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: GEOMETRY | Topic: Line Symmetry | Outcome: completing a symmetric figure with respect to a given line of symmetry on square grid\nloId: P4:GEOMETRY:5.4.1 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: GEOMETRY | Topic: Nets | Outcome: identifying 2D representations of • cube • cuboid • cone • cylinder • prism • pyramid\nloId: P4:GEOMETRY:5.4.2 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: GEOMETRY | Topic: Nets | Outcome: drawing 2D representations of • cube • cuboid • prism • pyramid\nloId: P4:GEOMETRY:5.4.3 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: GEOMETRY | Topic: Nets | Outcome: identifying the nets of 3D solids • cube • cuboid • prism • pyramid\nloId: P4:GEOMETRY:5.4.4 | Strand: MEASUREMENT AND GEOMETRY | SubStrand: GEOMETRY | Topic: Nets | Outcome: identifying the solid which can be formed by a given net\nloId: P4:DATA REPRESENTATION AND INTERPRETATION:6.1.1 | Strand: STATISTICS | SubStrand: DATA REPRESENTATION AND INTERPRETATION | Topic: Tables and Line Graphs | Outcome: completing a table/line graph from given data\nloId: P4:DATA REPRESENTATION AND INTERPRETATION:6.1.2 | Strand: STATISTICS | SubStrand: DATA REPRESENTATION AND INTERPRETATION | Topic: Tables and Line Graphs | Outcome: reading and interpreting data from a table/line graph\n'

In [36]:
# Configure Gemini
client = genai.Client(api_key=os.environ["API_KEY"])

def classification_engine(question_text):
    prompt = f"""    
    ### TASK:
    Find the EXACT matching entry from the SYLLABUS KNOWLEDGE BASE for the question provided.
    
    ### RULES:
    1. You MUST use one of the loIds provided in the list below.
    2. The 'strand', 'subStrand', 'topic', and 'learningOutcome' MUST be copied word-for-word from that specific loId entry.
    3. If multiple outcomes apply, pick the most specific one.

    ### SYLLABUS KNOWLEDGE BASE:
    {syllabus_knowledge_base}

    ### QUESTION TO CLASSIFY:
    "{question_text}"

    ### OUTPUT FORMAT (JSON ONLY):
    {{
      "strand": "...",
      "subStrand": "...",
      "topic": "...",
      "learningOutcome": "...",
      "loId": "..."
    }}
    """
    
    try:
        response = client.models.generate_content(
            model="gemini-3-flash-preview",
            contents=prompt,
        )
        clean_json = response.text.replace('```json', '').replace('```', '').strip()
        return json.loads(clean_json)
    except Exception as e:
        return {"error": str(e)}

# Test the engine once
print(classification_engine("Ethan left his home at 10:45 am and took 25 minutes to cycle to the hawker centre. After having his lunch, he left the hawker centre at 11:45 am. \n(a) How long was Ethan at the hawker centre?\n(b) From the hawker centre, Ethan cycled for 10 minutes to the supermarket. He spent 1 h 15 min in the supermarket before cycling home. What time did Ethan leave the supermarket?"))

{'strand': 'MEASUREMENT AND GEOMETRY', 'subStrand': 'MEASUREMENT', 'topic': 'Time', 'learningOutcome': 'finding the starting time, finishing time or duration given the other two quantities', 'loId': 'P3:MEASUREMENT:4.2.2'}

In [42]:
output_file = "classification_results.jsonl"
print("Starting classification...")

# 1. Check existing progress (Standard Resume Logic)
already_processed_count = 0
if os.path.exists(output_file):
    with open(output_file, 'r', encoding="utf-8") as f:
        already_processed_count = sum(1 for line in f)
print(f"Resuming from question {already_processed_count}...")

# 2. Open file in append mode
with open(output_file, "a", encoding="utf-8") as f:
    for index, row in df.iterrows():
        # Skip rows that are already saved in the file
        if index < already_processed_count:
            continue
            
        if index % 5 == 0: 
            print(f"Processing: {index}/{len(df)}")
        
        # Get prediction
        prediction = classification_engine(row['question'])
        
        # 3. MODIFIED ERROR HANDLING: Stop on error
        if not isinstance(prediction, dict) or "error" in prediction:
            error_msg = prediction.get('error', 'Unknown error')
            print(f"\n🛑 STOPPING: Error at index {index}: {error_msg}")
            print("You can run this cell again to resume from this exact point.")
            break  # This exits the loop and DOES NOT save the record
            
        # Construct the final record
        record = {
            "original_index": index,
            "question": row['question'],
            "expected_loId": row['label']['loId'], 
            **prediction 
        }
        
        # 4. Save to file
        f.write(json.dumps(record) + "\n")
        f.flush() 
        
        # API Rate Limit Safety
        time.sleep(4) 

# Only load final_df if the loop actually finished all questions
results = []
if os.path.exists(output_file):
    with open(output_file, 'r', encoding='utf-8') as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue # Skip empty lines
            try:
                results.append(json.loads(line))
            except json.JSONDecodeError:
                print(f"⚠️ Skipping corrupted data at line {line_num}")

    final_df = pd.DataFrame(results)
    
    if len(final_df) == len(df):
        print(f"\n✅ Finished! All {len(df)} results processed.")
    else:
        print(f"\n⚠️ Process paused. {len(final_df)}/{len(df)} questions completed.")

Starting classification...
Resuming from question 67...

✅ Finished! All 67 results processed.

In [ ]:
syllabus_lookup = syllabus_df.set_index('loId').to_dict('index')

# Function to safely get expected values
def get_expected_info(loId, field):
    if loId in syllabus_lookup:
        return syllabus_lookup[loId].get(field, "N/A")
    return "N/A"

# Create the missing 'expected_' columns in your results dataframe
for level in ['strand', 'subStrand', 'topic', 'learningOutcome']:
    final_df[f'expected_{level}'] = final_df['expected_loId'].apply(lambda x: get_expected_info(x, level))

In [48]:
def calculate_accuracy_report(df):
    """Calculates accuracy breakdown for Part B."""
    print("\n" + "="*60)
    print("      SINGAPORE MATH CLASSIFIER: ACCURACY REPORT")
    print("="*60)
    
    levels = ['strand', 'subStrand', 'topic', 'learningOutcome', 'loId']
    
    for level in levels:
        # Check if both columns exist
        pred_col = level
        expected_col = f'expected_{level}' if level != 'loId' else 'expected_loId'
        
        if pred_col in df.columns and expected_col in df.columns:
            # Calculate accuracy
            correct = (df[pred_col] == df[expected_col]).mean() * 100
            print(f"Accuracy [{level.upper():<15}]: {correct:>6.2f}%")
        else:
            print(f"Skipping [{level.upper()}]: Columns not found")
            
    print("="*60 + "\n")

def display_mismatches(df):
    """Shows comparison view for mismatches."""
    mismatches = df[df['loId'] != df['expected_loId']]
    
    print(f"--- Comparison View: Mismatches Found ({len(mismatches)}) ---")
    for i, row in mismatches.iterrows():
        print(f"Q: {row['question'][:80]}...")
        print(f"   - EXPECTED: {row['expected_loId']}")
        print(f"   - ENGINE  : {row['loId']}  <-- MISMATCH")
        print("-" * 30)

In [51]:
def run_cli():
    while True:
        print("\n--- MATH CLASSIFIER ENGINE MENU ---")
        print("1. Run all 67 API questions (Batch Test)")
        print("2. Test custom question (Manual Input)")
        print("3. Exit")
        
        choice = input("\nEnter your choice (1/2/3): ")
        
        if choice == '1':
            print("\nRunning Batch Processing...")
            # This triggers your loop logic from previous steps
            # Ensure final_df is generated here
            calculate_accuracy_report(final_df)
            
            show_details = input("Show comparison for mismatches? (y/n): ")
            if show_details.lower() == 'y':
                display_mismatches(final_df)
                
        elif choice == '2':
            custom_q = input("\nEnter math question: ")
            print("\nClassifying...")
            result = classification_engine(custom_q)
            print(json.dumps(result, indent=4))
            
        elif choice == '3':
            print("Exiting engine. Goodbye!")
            break
        else:
            print("Invalid choice, try again.")


run_cli()

--- MATH CLASSIFIER ENGINE MENU ---
1. Run all 67 API questions (Batch Test)
2. Test custom question (Manual Input)
3. Exit

Running Batch Processing...

============================================================
      SINGAPORE MATH CLASSIFIER: ACCURACY REPORT
============================================================
Accuracy [STRAND         ]:  97.01%
Accuracy [SUBSTRAND      ]:  97.01%
Accuracy [TOPIC          ]:  74.63%
Accuracy [LEARNINGOUTCOME]:  56.72%
Accuracy [LOID           ]:  55.22%
============================================================


--- MATH CLASSIFIER ENGINE MENU ---
1. Run all 67 API questions (Batch Test)
2. Test custom question (Manual Input)
3. Exit

Running Batch Processing...

============================================================
      SINGAPORE MATH CLASSIFIER: ACCURACY REPORT
============================================================
Accuracy [STRAND         ]:  97.01%
Accuracy [SUBSTRAND      ]:  97.01%
Accuracy [TOPIC          ]:  74.63%
Accuracy [LEARNINGOUTCOME]:  56.72%
Accuracy [LOID           ]:  55.22%
============================================================

--- Comparison View: Mismatches Found (30) ---
Q: What is the remainder when 3079 is divided by 8?...
   - EXPECTED: P3:WHOLE NUMBERS:1.3.3
   - ENGINE  : P4:WHOLE NUMBERS:1.3.2  <-- MISMATCH
------------------------------
Q: 5 x 6 = _____...
   - EXPECTED: P3:WHOLE NUMBERS:1.3.1
   - ENGINE  : P3:WHOLE NUMBERS:1.3.2  <-- MISMATCH
------------------------------
Q: I am a number between 20 and 40, You can find me in the multiplication tables of...
   - EXPECTED: P3:WHOLE NUMBERS:1.3.1
   - ENGINE  : P4:WHOLE NUMBERS:1.2.5  <-- MISMATCH
------------------------------
Q: Four students have written the following statements in their books. Which one of...
   - EXPECTED: P3:MEASUREMENT:4.1.3
   - ENGINE  : P4:WHOLE NUMBERS:1.2.1  <-- MISMATCH
------------------------------
Q: Find the value of 1/12 + 2/3. Express your answer as a fraction in its simplest ...
   - EXPECTED: P3:FRACTIONS:2.1.2
   - ENGINE  : P3:FRACTIONS:2.2.1  <-- MISMATCH
------------------------------
Q: Anne paid $720 for a pair of shoes and a belt. The pair of shoes cost 4 times as...
   - EXPECTED: P3:WHOLE NUMBERS:1.3.4
   - ENGINE  : P4:WHOLE NUMBERS:1.3.2  <-- MISMATCH
------------------------------
Q: Mrs Tan had some blueberries. She packed them equally into 9 boxes and found tha...
   - EXPECTED: P3:MEASUREMENT:4.1.2
   - ENGINE  : P3:MEASUREMENT:4.1.3  <-- MISMATCH
------------------------------
Q: Which of the following figures does not show 1/4 of the figure shaded?...
   - EXPECTED: P3:FRACTIONS:2.1.3
   - ENGINE  : P3:FRACTIONS:2.1.1  <-- MISMATCH
------------------------------
Q: What is the missing number in the pattern?
1620, 1720, 1820, 1920, _____, 2120...
   - EXPECTED: P3:WHOLE NUMBERS:1.1.1
   - ENGINE  : P3:WHOLE NUMBERS:1.1.5  <-- MISMATCH
------------------------------
Q: 9 hundreds x 4 = _____...
   - EXPECTED: P3:WHOLE NUMBERS:1.1.1
   - ENGINE  : P3:WHOLE NUMBERS:1.3.2  <-- MISMATCH
------------------------------
Q: Adam, Ben and Clarice shared a chocolate bar. Adam ate 5/12 of the chocolate bar...
   - EXPECTED: P3:FRACTIONS:2.2.1
   - ENGINE  : P4:FRACTIONS:2.3.1  <-- MISMATCH
------------------------------
Q: Mdm Owen had 17 stickers at first. Then, she bought 19 more stickers. She packed...
   - EXPECTED: P3:WHOLE NUMBERS:1.2.2
   - ENGINE  : P3:WHOLE NUMBERS:1.3.2  <-- MISMATCH
------------------------------
Q: Express 4 3/25 as a decimal....
   - EXPECTED: P4:DECIMALS:3.1.3
   - ENGINE  : P4:DECIMALS:3.1.4  <-- MISMATCH
------------------------------
Q: How many one-thirds are there in 5 wholes?...
   - EXPECTED: P4:FRACTIONS:2.2.1
   - ENGINE  : P4:FRACTIONS:2.1.1  <-- MISMATCH
------------------------------
Q: Ahmad and Bala had 180 erasers altogether.
Bala had three times as many erasers ...
   - EXPECTED: P4:WHOLE NUMBERS:1.3.2
   - ENGINE  : P3:WHOLE NUMBERS:1.3.4  <-- MISMATCH
------------------------------
Q: Which of the following figures does not have a line of symmetry...
   - EXPECTED: P4:GEOMETRY:5.3.2
   - ENGINE  : P4:GEOMETRY:5.3.1  <-- MISMATCH
------------------------------
Q: Jamie bought 8 boxes of biscuits. Each box of biscuits cost $1.20. She gave the ...
   - EXPECTED: P4:DECIMALS:3.2.1
   - ENGINE  : P4:DECIMALS:3.3.1  <-- MISMATCH
------------------------------
Q: In which of the following are the numbers arranged from the smallest to the grea...
   - EXPECTED: P4:WHOLE NUMBERS:1.1.3
   - ENGINE  : P3:WHOLE NUMBERS:1.1.4  <-- MISMATCH
------------------------------
Q: Tony listed the factors of 81 below.
1, 3, 81
He missed out two factors. What ar...
   - EXPECTED: P4:WHOLE NUMBERS:1.2.2
   - ENGINE  : P4:WHOLE NUMBERS:1.2.1  <-- MISMATCH
------------------------------
Q: There were twice as many women as men at a carnival. After 180 women left the ca...
   - EXPECTED: P4:WHOLE NUMBERS:1.3.1
   - ENGINE  : P3:WHOLE NUMBERS:1.3.4  <-- MISMATCH
------------------------------
Q: A bag of sand had a mass of 109 kg. It was repacked into 7 sacks. What was the m...
   - EXPECTED: P4:DECIMALS:3.3.2
   - ENGINE  : P4:DECIMALS:3.3.3  <-- MISMATCH
------------------------------
Q: Express 87/100 as a decimal....
   - EXPECTED: P4:DECIMALS:3.1.3
   - ENGINE  : P4:DECIMALS:3.1.4  <-- MISMATCH
------------------------------
Q: Round 26 510 to the nearest hundred....
   - EXPECTED: P4:WHOLE NUMBERS:1.1.6
   - ENGINE  : P4:WHOLE NUMBERS:1.1.5  <-- MISMATCH
------------------------------
Q: Muthu has fewer than 50 comic books.
If he gives all his comic books equally to ...
   - EXPECTED: P4:WHOLE NUMBERS:1.2.4
   - ENGINE  : P4:WHOLE NUMBERS:1.2.1  <-- MISMATCH
------------------------------
Q: Vincent mixed 6.4 ℓ of blue paint with 7 ℓ if white paint. After he poured some ...
   - EXPECTED: P4:DECIMALS:3.1.5
   - ENGINE  : P4:DECIMALS:3.3.3  <-- MISMATCH
------------------------------
Q: At first, there were a total of 1638 children at a carnival. After 1/2 of the bo...
   - EXPECTED: P4:FRACTIONS:2.3.1
   - ENGINE  : P4:FRACTIONS:2.2.1  <-- MISMATCH
------------------------------
Q: Aini, Kathy and Mandy formed a team to compete a 4-km race. Aini ran 3/4 km. The...
   - EXPECTED: P4:FRACTIONS:2.1.2
   - ENGINE  : P4:FRACTIONS:2.3.1  <-- MISMATCH
------------------------------
Q: The total mass of an empty school bag and 5 similar books was 5.4 kg. The total ...
   - EXPECTED: P4:DECIMALS:3.2.1
   - ENGINE  : P4:DECIMALS:3.3.1  <-- MISMATCH
------------------------------
Q: A bookshop sold any 3 items for $5. To celebrate SG60, the bookshop gave away 1 ...
   - EXPECTED: P4:WHOLE NUMBERS:1.3.1
   - ENGINE  : P3:WHOLE NUMBERS:1.3.4  <-- MISMATCH
------------------------------
Q: A school printed a total of 4398 worksheets on Monday, Tuesday and Wednesday. it...
   - EXPECTED: P4:WHOLE NUMBERS:1.3.1
   - ENGINE  : P4:WHOLE NUMBERS:1.3.2  <-- MISMATCH
------------------------------

--- MATH CLASSIFIER ENGINE MENU ---
1. Run all 67 API questions (Batch Test)
2. Test custom question (Manual Input)
3. Exit

Running Batch Processing...

============================================================
      SINGAPORE MATH CLASSIFIER: ACCURACY REPORT
============================================================
Accuracy [STRAND         ]:  97.01%
Accuracy [SUBSTRAND      ]:  97.01%
Accuracy [TOPIC          ]:  74.63%
Accuracy [LEARNINGOUTCOME]:  56.72%
Accuracy [LOID           ]:  55.22%
============================================================

--- Comparison View: Mismatches Found (30) ---
Q: What is the remainder when 3079 is divided by 8?...
   - EXPECTED: P3:WHOLE NUMBERS:1.3.3
   - ENGINE  : P4:WHOLE NUMBERS:1.3.2  <-- MISMATCH
------------------------------
Q: 5 x 6 = _____...
   - EXPECTED: P3:WHOLE NUMBERS:1.3.1
   - ENGINE  : P3:WHOLE NUMBERS:1.3.2  <-- MISMATCH
------------------------------
Q: I am a number between 20 and 40, You can find me in the multiplication tables of...
   - EXPECTED: P3:WHOLE NUMBERS:1.3.1
   - ENGINE  : P4:WHOLE NUMBERS:1.2.5  <-- MISMATCH
------------------------------
Q: Four students have written the following statements in their books. Which one of...
   - EXPECTED: P3:MEASUREMENT:4.1.3
   - ENGINE  : P4:WHOLE NUMBERS:1.2.1  <-- MISMATCH
------------------------------
Q: Find the value of 1/12 + 2/3. Express your answer as a fraction in its simplest ...
   - EXPECTED: P3:FRACTIONS:2.1.2
   - ENGINE  : P3:FRACTIONS:2.2.1  <-- MISMATCH
------------------------------
Q: Anne paid $720 for a pair of shoes and a belt. The pair of shoes cost 4 times as...
   - EXPECTED: P3:WHOLE NUMBERS:1.3.4
   - ENGINE  : P4:WHOLE NUMBERS:1.3.2  <-- MISMATCH
------------------------------
Q: Mrs Tan had some blueberries. She packed them equally into 9 boxes and found tha...
   - EXPECTED: P3:MEASUREMENT:4.1.2
   - ENGINE  : P3:MEASUREMENT:4.1.3  <-- MISMATCH
------------------------------
Q: Which of the following figures does not show 1/4 of the figure shaded?...
   - EXPECTED: P3:FRACTIONS:2.1.3
   - ENGINE  : P3:FRACTIONS:2.1.1  <-- MISMATCH
------------------------------
Q: What is the missing number in the pattern?
1620, 1720, 1820, 1920, _____, 2120...
   - EXPECTED: P3:WHOLE NUMBERS:1.1.1
   - ENGINE  : P3:WHOLE NUMBERS:1.1.5  <-- MISMATCH
------------------------------
Q: 9 hundreds x 4 = _____...
   - EXPECTED: P3:WHOLE NUMBERS:1.1.1
   - ENGINE  : P3:WHOLE NUMBERS:1.3.2  <-- MISMATCH
------------------------------
Q: Adam, Ben and Clarice shared a chocolate bar. Adam ate 5/12 of the chocolate bar...
   - EXPECTED: P3:FRACTIONS:2.2.1
   - ENGINE  : P4:FRACTIONS:2.3.1  <-- MISMATCH
------------------------------
Q: Mdm Owen had 17 stickers at first. Then, she bought 19 more stickers. She packed...
   - EXPECTED: P3:WHOLE NUMBERS:1.2.2
   - ENGINE  : P3:WHOLE NUMBERS:1.3.2  <-- MISMATCH
------------------------------
Q: Express 4 3/25 as a decimal....
   - EXPECTED: P4:DECIMALS:3.1.3
   - ENGINE  : P4:DECIMALS:3.1.4  <-- MISMATCH
------------------------------
Q: How many one-thirds are there in 5 wholes?...
   - EXPECTED: P4:FRACTIONS:2.2.1
   - ENGINE  : P4:FRACTIONS:2.1.1  <-- MISMATCH
------------------------------
Q: Ahmad and Bala had 180 erasers altogether.
Bala had three times as many erasers ...
   - EXPECTED: P4:WHOLE NUMBERS:1.3.2
   - ENGINE  : P3:WHOLE NUMBERS:1.3.4  <-- MISMATCH
------------------------------
Q: Which of the following figures does not have a line of symmetry...
   - EXPECTED: P4:GEOMETRY:5.3.2
   - ENGINE  : P4:GEOMETRY:5.3.1  <-- MISMATCH
------------------------------
Q: Jamie bought 8 boxes of biscuits. Each box of biscuits cost $1.20. She gave the ...
   - EXPECTED: P4:DECIMALS:3.2.1
   - ENGINE  : P4:DECIMALS:3.3.1  <-- MISMATCH
------------------------------
Q: In which of the following are the numbers arranged from the smallest to the grea...
   - EXPECTED: P4:WHOLE NUMBERS:1.1.3
   - ENGINE  : P3:WHOLE NUMBERS:1.1.4  <-- MISMATCH
------------------------------
Q: Tony listed the factors of 81 below.
1, 3, 81
He missed out two factors. What ar...
   - EXPECTED: P4:WHOLE NUMBERS:1.2.2
   - ENGINE  : P4:WHOLE NUMBERS:1.2.1  <-- MISMATCH
------------------------------
Q: There were twice as many women as men at a carnival. After 180 women left the ca...
   - EXPECTED: P4:WHOLE NUMBERS:1.3.1
   - ENGINE  : P3:WHOLE NUMBERS:1.3.4  <-- MISMATCH
------------------------------
Q: A bag of sand had a mass of 109 kg. It was repacked into 7 sacks. What was the m...
   - EXPECTED: P4:DECIMALS:3.3.2
   - ENGINE  : P4:DECIMALS:3.3.3  <-- MISMATCH
------------------------------
Q: Express 87/100 as a decimal....
   - EXPECTED: P4:DECIMALS:3.1.3
   - ENGINE  : P4:DECIMALS:3.1.4  <-- MISMATCH
------------------------------
Q: Round 26 510 to the nearest hundred....
   - EXPECTED: P4:WHOLE NUMBERS:1.1.6
   - ENGINE  : P4:WHOLE NUMBERS:1.1.5  <-- MISMATCH
------------------------------
Q: Muthu has fewer than 50 comic books.
If he gives all his comic books equally to ...
   - EXPECTED: P4:WHOLE NUMBERS:1.2.4
   - ENGINE  : P4:WHOLE NUMBERS:1.2.1  <-- MISMATCH
------------------------------
Q: Vincent mixed 6.4 ℓ of blue paint with 7 ℓ if white paint. After he poured some ...
   - EXPECTED: P4:DECIMALS:3.1.5
   - ENGINE  : P4:DECIMALS:3.3.3  <-- MISMATCH
------------------------------
Q: At first, there were a total of 1638 children at a carnival. After 1/2 of the bo...
   - EXPECTED: P4:FRACTIONS:2.3.1
   - ENGINE  : P4:FRACTIONS:2.2.1  <-- MISMATCH
------------------------------
Q: Aini, Kathy and Mandy formed a team to compete a 4-km race. Aini ran 3/4 km. The...
   - EXPECTED: P4:FRACTIONS:2.1.2
   - ENGINE  : P4:FRACTIONS:2.3.1  <-- MISMATCH
------------------------------
Q: The total mass of an empty school bag and 5 similar books was 5.4 kg. The total ...
   - EXPECTED: P4:DECIMALS:3.2.1
   - ENGINE  : P4:DECIMALS:3.3.1  <-- MISMATCH
------------------------------
Q: A bookshop sold any 3 items for $5. To celebrate SG60, the bookshop gave away 1 ...
   - EXPECTED: P4:WHOLE NUMBERS:1.3.1
   - ENGINE  : P3:WHOLE NUMBERS:1.3.4  <-- MISMATCH
------------------------------
Q: A school printed a total of 4398 worksheets on Monday, Tuesday and Wednesday. it...
   - EXPECTED: P4:WHOLE NUMBERS:1.3.1
   - ENGINE  : P4:WHOLE NUMBERS:1.3.2  <-- MISMATCH
------------------------------

--- MATH CLASSIFIER ENGINE MENU ---
1. Run all 67 API questions (Batch Test)
2. Test custom question (Manual Input)
3. Exit
Exiting engine. Goodbye!